version: '3.4'

services:
  person.database:
    image: postgres:latest
    container_name: person.database
    environment:
      - POSTGRES_HOST=person.database
      - POSTGRES_DB=TeachersRate
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password12345
    # volumes:
    #   - ./.containers/person-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
       
  teacherrate.api:
    container_name: teacher-rate-backend
    image: ${DOCKER_REGISTRY-}teacherrateproject
    build:
      context: .
      dockerfile: TeacherRate.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - person.database
    environment:
      - DB_HOST=person.database
      - DB_PORT=5432
      - DB_NAME=TeachersRate
      - DB_USER=user
      - DB_PASSWORD=password12345
      - APP_SETTINGS=Development 
