version: '3.4'

networks:
  teacherratebackend:

services:
  demoappdb:
    container_name: app-db
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
      - MSSQL_PID=Express
    networks:
      - teacherratebackend
       
  teacherrateproject:
    container_name: teacher-rate-backend
    image: ${DOCKER_REGISTRY-}teacherrateproject
    build:
      context: .
      dockerfile: TeacherRateProject/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - demoappdb
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=TeacherRateDB
      - DB_PASSWORD=password@12345#
    networks:
      - teacherratebackend
